version: '{build}'
branches:
  only:
  - master
  - /^v\d+(?:\.\d+)?$/
  - /[\b_]validate\b/
skip_tags: true
nuget:
  disable_publish_on_pr: true
image: Visual Studio 2017
configuration: Release
environment:
  VisualStudioVersion: 15.0
  TreatWarningsAsErrors: true
  CodeAnalysisTreatWarningsAsErrors: true
before_build:
  msbuild src\Nerdbank.Algorithms.sln /nologo /m /v:quiet /t:restore
build_script:
- msbuild src\Nerdbank.Algorithms.sln /nologo /m /fl /v:minimal /t:build,pack
test_script:
- dotnet test .\src\NerdBank.AlgorithmsTest\NerdBank.AlgorithmsTest.csproj --no-build
artifacts:
- path: bin\**\*.nupkg
  name: NuGet Package
